---
# clip cleanup
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bucket-cleanup
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  schedule: "0 4 * * *" #every day at 4am
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bucket-cleanup
            image: "busybox:1.32"
            command: ["/bin/sh", "-c"]
            args:
            - echo staring;
              echo cleaning crops folder;
              \[ -d /mnt/innovi-data/crops \] && find /mnt/innovi-data/crops/ -type f -mtime +2 -delete || echo innovi-data/crops folder does not exist;
              \[ -d /mnt/innovi-data/search \] && find /mnt/innovi-data/search/ -type f -mtime +2 -delete || echo innovi-data/search folder does not exist;
              echo cleaning events folder;
              find /mnt/innovi-data/events/ -type f -mtime +30 -delete;
              echo done
            volumeMounts:
            - name: innovi-data
              mountPath: /mnt/innovi-data/
          volumes:
          - name: innovi-data
            persistentVolumeClaim:
              claimName: innovi-data
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - innovi-core-api
                topologyKey: "kubernetes.io/hostname"
          restartPolicy: Never
